### PR TITLE
Update for GPUCompiler v0.21

### PR DESCRIPTION
**Pull request by tshort**

### CODE REVIEW

**Comment by tshort** [comment]
Upgrading GPUCompiler didn't fix failures on macOS ☹️. Nightlies are all still failing, too.

**Comment by brenhinkeller** [comment]
The failures in `parsedlm` are something that needs to be fixed over in statictools (used to be only on aarch64 but maybe on all apple now?) but I think we can just label those as broken, let's see how much closer this gets us...

**Comment by MasonProtter** [comment]
I don't know if this is related, but `@device_override` is completely broken and I'm not sure if it ever worked. I can't find a commit right now where it worked at least. 

Did anyone test it?
```julia
julia> using StaticCompiler, StaticTools

julia> f() = printf(c"the value is: %d\n", 1);

julia> StaticCompiler.@device_override f() = printf(c"the value is: %d\n", 2);

julia> compile_executable(f, (), "./") # compile it to an execuable
"/home/mason/f"

julia> run(`./f`) # run it
the value is: 1
Process(`./f`, ProcessExited(0))

```

**Comment by brenhinkeller** [comment]
Hmm, could that be some weird world age issue or something? The versions defined in https://github.com/tshort/StaticCompiler.jl/blob/master/src/quirks.jl seem to be doing something because without them https://github.com/tshort/StaticCompiler.jl/blob/master/test/scripts/throw_errors.jl wouldn't compile, IIRC

**Comment by brenhinkeller** [comment]
Ok, looks like we're back to being fine except for Nightly now

**Comment by tshort** [comment]
Should we stop testing nightly now, too?

It looks like it's hitting an error in `optimize!`, so something must have changed there.

**Comment by brenhinkeller** [comment]
I'd leave the nightly tests since it's always good to know what's coming --- they show up in a different badge on the repo anyways so the main two badges should be green after merging this. The red nightly can just be an encouragement to go raise the issue on Slack if things stay broken there and a release is coming...

**Comment by tshort** [comment]
Ahh. Good to know.

**Pull request merged**
