### PR TITLE
Adds Docs + workflow utilities

### PR DESCRIPTION
**Pull request by aminya**
- Adds documentation
- Adds docs.yml using Github Actions
- Adds ci.yml using Github Actions
- Adds TagBot using Github Actions
- Adds CompatHelper using Github Actions
- Allowing loading without gcc

To make automatic deployment work:
```julia
# ]add DocumenterTools
using StaticCompiler, DocumenterTools
DocumenterTools.genkeys(StaticCompiler)
```
Add the public key to https://github.com/tshort/StaticCompiler.jl/settings/keys
Add the private key to https://github.com/tshort/StaticCompiler.jl/settings/secrets

### CODE REVIEW

**Comment by tshort** [comment]
Looks good to me. I'll plan on merging this weekend. It's interesting to see the latest on Julia package docs and other features. Thanks for the directions, too.

**Comment by aminya** [comment]
> 
> 
> Looks good to me. I'll plan on merging this weekend. It's interesting to see the latest on Julia package docs and other features. Thanks for the directions, too.

You're welcome! 

P.S: you can remove Travis and Appveyor toml files too and only use Github Actions (which is faster and better IMO).

**Comment by tshort** [comment]
Okay, this PR is merged, and I added the public and private keys. Does something else need to be done to trigger docs?

**Comment by aminya** [comment]
Ahh, I just forgot that StaticCompiler is not registered yet.
The run here fails to add StaticCompiler.
https://github.com/tshort/StaticCompiler.jl/runs/448105083?check_suite_focus=true#step:4:11

1) we can register StaticCompiler and fix the error
2) I can add a line to add StaticCompiler based on the link.

I will 2 for now until you register.

**Pull request merged**
