### PR TITLE
Upgrade to GPUCompiler v0.19

### PR DESCRIPTION
**Pull request by tshort**
GPUCompiler no longer prepends "julia_". I kept that approach in this update.

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Oh awesome!

**Comment by brenhinkeller** [comment]
Was it easy enough to integrate that with the `demangle` kwarg / should we add that option in more places?

**Comment by brenhinkeller** [comment]
Yeah, I think it's not in the test suite it's probably not handled right for a couple GPUCompiler versions.. but could fix that later if you want to merge this!

**Comment by tshort** [comment]
Okay, we'll go with the merge now and look at demangle later.

**Pull request merged**
