### PR TITLE
Refactor code to make it more amenable to cross compilation

### PR DESCRIPTION
**Pull request by gbaraldi**
Also cleanup some of it.

This doesn't allow for actual cross-compilation because we need the compilers, and implementing that is basically implementing BinaryBuilder, but maybe we should add an option to pass `cc`.

### CODE REVIEW

**Comment by tshort** [comment]
Plus one from me. Could you add an example in the docs or maybe even a test of a cross compilation? Cross compiling to WebAssembly should work because that's built into the compiler.

Do any of the compilers in Yggdrasil provide cross compilation?

**Comment by gbaraldi** [comment]
Yggy has tons of cross compilers, but they only run in linux.

**Review by MasonProtter — APPROVED** [review]
Looks good to me. Would you mind bumping the major version and then I think this is ready to go. Fixes for nightly can be done later once the interfaces and such in nightly stabilize a bit.

**Comment by tshort** [comment]
Sorry. No one pulled the trigger here. Anything else we need to do here?

**Pull request merged**
