### PR TITLE
Remove JLD2 from Project.toml

### PR DESCRIPTION
**Pull request by brenhinkeller**
This seems was blocking registration since it didn't have compat bounds, but AFAICT isn't being used any more anyways!

### CODE REVIEW

**Review by Moelf — APPROVED** [review]

**Comment by Moelf** [comment]
can https://github.com/tshort/StaticCompiler.jl/blob/master/Manifest.toml just be removed entirely?

**Comment by brenhinkeller** [comment]
Oh good point, I normally do remove that from my packages before registration anyways.

**Comment by MasonProtter** [comment]
yeah let's do that

**Comment by brenhinkeller** [comment]
I wonder if Mason or Tom have preferences on that

**Comment by brenhinkeller** [comment]
Hah, I'm slow

**Comment by MasonProtter** [comment]
I meant to remove it a while ago and forgot

**Pull request merged**
