### PR TITLE
Helpers to compile to WebAssembly

### PR DESCRIPTION
**Pull request by tshort**
Inspired by @Alexander-Barth's [FluidSimDemo-WebAssembly](https://github.com/Alexander-Barth/FluidSimDemo-WebAssembly).

I'm working on an example [here](https://github.com/tshort/Lorenz-WebAssembly-Model.jl).

This code adds the option to remove address spaces. Compilation to WebAssembly requires that (LLVM's driver for wasm32 doesn't like those). One issue is that it conflicts with pointer patching stuff [here](https://github.com/tshort/StaticCompiler.jl/blob/0034adc704d675ad6ee742f92a7eb96fa19b0048/src/pointer_patching.jl#L141). So, code that needs pointer patching won't compile to WebAssembly.

### CODE REVIEW

**Comment by brenhinkeller** [comment]
Cool!

**Comment by Alexander-Barth** [comment]
I am wondering what kind of error you had without this option ( remove address spaces) ? I am asking because I did not use any special flag myself.

I am curious to see the Lorenz System using Julia/WASM :-)

**Comment by tshort** [comment]
@Alexander-Barth, your conversion to WebAssembly didn't give an error because it uses GPUCompiler's default optimization pipeline. That removes address spaces [here](https://github.com/JuliaGPU/GPUCompiler.jl/blob/81a181d3304ede4c3790087180b9a4cd1db3ca95/src/optim.jl#L217). StaticCompiler uses an optimization pipeline from Enzyme (I'm not sure why--Mason would know). The Enzyme pipeline doesn't remove address spaces, and without that, the compilation failed. I don't remember what the error was. Your code helped me figure this out, because your code worked, and this didn't without that change.

I hope to get the DiffEq demo running online this weekend.

**Comment by tshort** [comment]
> Is this the most promising way of compiling for WASM right now? (As opposed to seemingly abandoned [Keno/julia-wasm](https://github.com/Keno/julia-wasm))

Keno managed to compile most of Julia, so you get a complete interactive environment. That's impressive. It's also a rather large download. So while it's great for interactivity, it's not great for focused web apps.

StaticCompiler can compile select methods to WebAssembly, so the result is a small WebAssembly file. That's nice for web apps. But, you can only compile a subset of Julia code. Hopefully, it's enough to be valuable for a lot of scientific code.

**Comment by tshort** [comment]
@Alexander-Barth, on the 64-bit compilation, I've used 64-bit Julia to compile to wasm32. I don't think the address spaces impact that. There are some places where you end up with 64-bit integers because of the use of `Int` or from integer constants. It can still be okay for a lot of code. Those 64-bit integers just take up more space, but WebAssembly can still handle them. It's probably safer to use 32-bit Julia, and the code will be a bit smaller.

**Comment by MasonProtter** [comment]
> One issue is that it conflicts with pointer patching stuff [here](https://github.com/tshort/StaticCompiler.jl/blob/0034adc704d675ad6ee742f92a7eb96fa19b0048/src/pointer_patching.jl#L141).

The whole pointer patching code path should only be hit when you're using `compile` to pull the compiled code into a running julia session anyways, so I think there's no problem there.

> StaticCompiler uses an optimization pipeline from Enzyme (I'm not sure why--Mason would know).

If I remember correctly, it basically came down to the fact that the julia pipeline wasn't modular enough for me when I was trying to avoid certain code transformations the compiler does when it generates code that's meant to be run in-session.

**Comment by Alexander-Barth** [comment]
Thanks a lot for these explanations, Tom !

**Comment by geordie2020** [comment]
@tshort 
Thank you for the explanation! I'm fairly new to Julia and this is a bit above my head.

**Comment by tshort** [comment]
Here's my DiffEq web app using the newly merged and tagged WebAssembly support:

https://tshort.github.io/Lorenz-WebAssembly-Model.jl/

**Comment by MasonProtter** [comment]
Very cool Tom!

**Pull request merged**
