### PR TITLE
Major cleanup. Remove `compile`,  `compile_wasm`, and `MixTape`

### PR DESCRIPTION
**Pull request by MasonProtter**
This removes the `compile` functionality (closes https://github.com/tshort/StaticCompiler.jl/issues/119), and does some general cleanup and fixes.

Before we merge this though, I'd also like to also discuss removing 

+ the `Mixtape` stuff since I'm not really convinced it's worth the maintenance burden when we already have `@device_override` which is easier to use, and doesn't rely on the broken, unmaintained CodeInfoTools.jl. `@device_override` should cover every reasonable usecase as far as I'm aware. 
+ The `wasm` stuff because https://github.com/tshort/WebAssemblyCompiler.jl exists and appears to work, whereas I'm not sure the wasm stuff in here works or not. Alternative we could look at bringing the functionality from that package in to here. cc @tshort

### CODE REVIEW

**Comment by MasonProtter** [comment]
Failing integration tests appear to be because of `wasm`.

**Comment by tshort** [comment]
Thumbs up on this PR. I looked over the code, but I didn't really do a code review. If it passes tests, I'm good.

I'm okay with removing both the Mixtape and the wasm support. For wasm, I think WebAssemblyCompiler will (should) compile more code and offer more capability. I agree that the `@device_override` is way easier than Mixtape. For code I'm using (mainly WebAssemblyCompiler), I've used the overlays a lot but haven't needed Mixtape.

**Comment by tshort** [comment]
As part of the cutting of features, I would like to keep the cross-compiling support.

**Review by brenhinkeller — APPROVED** [review]
This looks good to me! This package has really come a long way and taught us all a lot I think. This slimming-down should be great for the maintenance burden going forward, and anyone can always check out the older versions if they want to see all the other things we experimented with

**Comment by MasonProtter** [comment]
Okay, I've removed the wasm stuff, and the mixtape stuff. I also added an ability to specify your own `method_table` during compilation, in case there are cases where someone wants to do a certain overload just for a certain function they want to compile, but don't want to pollute the `StaticCompiler` wider method-table.

**Comment by brenhinkeller** [comment]
Hooray!

**Pull request merged**
