### PR TITLE
Automatic LLVM installation

### PR DESCRIPTION
**Pull request by aminya**
Fixes https://github.com/tshort/StaticCompiler.jl/issues/7

[WIP]

### CODE REVIEW

**Comment by tshort** [comment]
Interesting. 

I think @maleadt is looking to do the same as part of LLVM.jl (based on a tidbit on Slack). If that happens, we might get it for free. He mentioned a concern of needing to match Julia's version of LLVM with the downloaded version. Not sure how that will happen.

**Comment by aminya** [comment]
That's a good point. I think it is better to move the code to LLVM.jl itself, so everyone one including us can use it.

**Comment by maleadt** [comment]
This is not going to work, for now. Adding a dependency on LLVM_jll requires you to pick a version, which in turn is going to pull in binaries according to that version, and not by matching the LLVM version that Julia provides. In that case, there will be incompatibilities between, e.g., the IR delivered by Julia and the LLVM library from LLVM_jll to process that IR.

**Comment by aminya** [comment]
But can't we find the LLVM version?
https://github.com/JuliaLang/julia/blob/master/src/llvm-version.h

**Comment by maleadt** [comment]
That is unrelated, and not used by e.g. Pkg to select which _package version_ of LLVM_jll to install.

**Comment by aminya** [comment]
I am going to close this here. If anything is going to be made, it should be on LLVM or PackageCompiler.

**Pull request closed without merging**
