### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by tshort**
Did I miss anyone?

### CODE REVIEW

**Comment by tshort** [comment]
Any idea why `Julia nightly - macOS-latest - x64` started failing?

**Comment by brenhinkeller** [comment]
Oh yeah, I was wondering about that
```
  UndefVarError: libLLVMExtra not defined
```
I was tentatively assuming that might just be nightly's fault (IIRC there was a Slack post recently about latest master being broken on mac anyways), but maybe Mason will have an idea

**Comment by MasonProtter** [comment]
Yeah, I assume it’s just the normal instabilities with Nightly.

**Comment by brenhinkeller** [comment]
LGTM :)

**Comment by MasonProtter** [comment]
Okay, I'm gonna merge and tag this so it ships with the registered version then

**Comment by jpsamaroo** [comment]
The libLLVMExtra error is probably https://github.com/maleadt/LLVM.jl/issues/291

**Pull request merged**
